pipeline{
    agent any
   
    tools { 
        maven 'Maven'
        jdk 'jdk'
      
    }
        stages{
            stage('Git-Checkout')
            {
                steps{
                     git 'https://github.com/sreelakshmi665/trailHello.git'
                }
            }
             stage('Clean')
        {
            steps{
                bat 'mvn -f trail/pom.xml clean'
            }
        }
            
             stage('Validate')
        {
            steps{
                bat 'mvn -f trail/pom.xml validate'
            }
        }
        stage('Compile')
        {
            steps{
                bat 'mvn -f trail/pom.xml compile'
            }
        }
        stage('sonar analysis'){
            steps{
                withSonarQubeEnv('sonar-server'){
                    withMaven(maven:'Maven'){
                        bat 'mvn -f trail/pom.xml sonar:sonar'
                    }
                }
            }
        }
            stage("Quality gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
        stage('Test')
        {
            steps{
                bat 'mvn -f trail/pom.xml test'
            }
        }
        stage('Package')
        {
            steps{
                bat 'mvn -f trail/pom.xml package'
            }
        }
        stage('Verify')
        {
            steps{
                bat 'mvn -f trail/pom.xml verify'
            }
        }
        stage('Install')
        {
            steps{
                bat 'mvn -f trail/pom.xml install'
            }
        }
            stage('Artifactory')
    {
      steps{
        archiveArtifacts artifacts:'trail/target/*.jar',followSymlinks:false
      }
    }
    stage('Deploy-To-Artifactory')
    {
      steps{
        rtUpload(
          serverId:'artifactory-server',
          spec: '''{
          "files": [
            {
              "pattern": "trail/target/*.jar",
              "target": "art-doc-dev-loc"
            }
         ]
    }''',
)
  }
}
        
           
        }
    post {  
         always {  
             echo 'This will always run'  
         }  
         success {  
             echo 'This will run only if successful'  
         }  
         failure {  
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sreelakshmilucky14@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sreelakshmilucky14@gmail.com";  
         }  
         unstable {  
             echo 'This will run only if the run was marked as unstable'  
         }  
         changed {  
             echo 'This will run only if the state of the Pipeline has changed'  
             echo 'For example, if the Pipeline was previously failing but is now successful'  
         } 
     }      
            
}
